project:
  type: website
  output-dir: _site

website:
  title: "HolzTank"
  site-url: https://holztank.top/
  description: "Un sitio hecho con Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: cursos.qmd
        text: Cursos
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: Acerca de
  page-footer:
    center: "Hecho con R y Quarto"

format:
  html:
    theme:
        dark: cyborg
        light: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



