# Introducción a los Proyectos de inversión

Si a un plan le asignamos recursos de distinta índole y produce bienes o servicios útiles, estamos hablando de un proyecto de inversión.

Cuando hablamos de inversión, no nos referimos únicamente a la generación de dinero. También podemos estar hablando de bienestar para la población, reducción de tiempo, ahorro de fondos, acceso a salud, satisfacción de necesidades individuales y colectivas y más tipos de beneficios.

Debemos considerar que no solo invierten las empresas privadas (que naturalmente buscan lucrar), si no también entidades gubernamentales que, idealmente, persiguen el realizar proyectos que mejoren la calidad de vida de los habitantes.

## Tipos de proyectos de inversión

Podemos clasificar los proyectos de inversión en tres categorías:

1. **Por categoría**. Producción de bienes o prestación de servicios.
2. **Actividad económica**. Se categoriza dependiendo del sector económico que atienden: agropecuario, industrial, de servicios, turísticos.
3. **Entidad u origen del recurso**. Aquí dividimos en proyectos de inversión privados o de carácter social. Los primeros tratan de satisfacer una demanda real en el mercado mientras persiguen la rentabilidad al hacerlo, mediante ciertos criterios. Por otro lado, las inversiones de tipo público van sobre la mejora de la calidad de vida de la comunidad a través de la prestación de un servicio o del suministro de un producto.

## Ciclo de vida de un proyecto

### Idea

### Preinversión

### Inversión

### Operación

