project:
  type: book

book:
  title: "Sistemas Embebidos"
  author: "Luis Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - introSist.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        dark: darkly
        light: flatly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml

